kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.acceleration-a.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.acceleration-a.name }}
  ports:
  - protocol: TCP
    port: {{.Values.acceleration-a.containerPort }}
    nodePort: {{.Values.acceleration-a.containerPort }}
