kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.acceleration-a.name }}
spec:
  selector:
    app: {{ .Values.acceleration-a.name }}
  ports:
  - protocol: TCP
    port: {{.Values.acceleration-a.containerPort }}
